name: SB-Skylands
version: "1.10"
main: de.sirati97.sb.skylands.SkylandsPlugin
description: The SB-Skylands Generator for 1.10
author: Jenkins
authors: ['Other Autors of SkylandsPlus','sirati97']
load: startup
softdepend: ['SB-Base']
loadbefore: ['SB-Plots']